language: node_js
node_js:
- '4'
env:
- CXX=g++-4.8
addons:
  apt:
    ssh_known_hosts: 128.199.215.215
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- bash _bash_scripts/install.sh 
after_success:
- bash _bash_scripts/deploy.sh
